import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const DEFAULT_MODEL = 'claude-haiku-4-5';
export const DEFAULT_DAILY_LIMIT = 300;
// Generated by `npm run kb:export` from frontend/src/content/profile.js.
export const SYSTEM_PROMPT_PATH = fileURLToPath(new URL('../assistant/system-prompt.md', import.meta.url));

// Values copied straight from .env.example look like "<your-anthropic-api-key>".
const isPlaceholder = (value) => /[<>]/.test(value);
const clean = (value) => (typeof value === 'string' ? value.trim() : '');

function readSystemPrompt(path) {
  try {
    return readFileSync(path, 'utf8').trim();
  } catch {
    return '';
  }
}

/**
 * Resolve the AI assistant configuration. Never throws: returns { enabled: false, reason }
 * when the assistant can't be used, so the server still boots.
 */
export function resolveAssistantConfig(env = process.env, { systemPrompt } = {}) {
  const apiKey = clean(env.ANTHROPIC_API_KEY);
  const model = clean(env.ANTHROPIC_MODEL) || DEFAULT_MODEL;
  const parsedLimit = Number.parseInt(clean(env.CHAT_DAILY_LIMIT), 10);
  const dailyLimit = Number.isFinite(parsedLimit) && parsedLimit >= 0 ? parsedLimit : DEFAULT_DAILY_LIMIT;
  const prompt = systemPrompt ?? readSystemPrompt(SYSTEM_PROMPT_PATH);

  if (!apiKey) return { enabled: false, reason: 'set ANTHROPIC_API_KEY' };
  if (isPlaceholder(apiKey))
    return { enabled: false, reason: 'ANTHROPIC_API_KEY still contains a placeholder (<...>)' };
  if (!prompt)
    return { enabled: false, reason: 'backend/assistant/system-prompt.md is missing – run `npm run kb:export`' };

  return { enabled: true, apiKey, model, dailyLimit, systemPrompt: prompt };
}

/** One human-readable status line for startup logs. Never includes secrets. */
export function describeAssistantConfig(config) {
  return config.enabled
    ? `Chatbot: enabled (${config.model}, daily limit ${config.dailyLimit || 'off'})`
    : `Chatbot: DISABLED – ${config.reason}`;
}
