import { readFileSync } from 'node:fs';

// Generated by `npm run kb:export` from frontend/src/content/profile.js.
const GITHUB_CONFIG_URL = new URL('../content/github.json', import.meta.url);

/** GitHub feed settings: generated profile data plus the optional GITHUB_TOKEN from the environment. */
export function resolveGitHubConfig(env = process.env) {
  const { username, featuredRepos, hiddenRepos, externalRepos } = JSON.parse(readFileSync(GITHUB_CONFIG_URL, 'utf8'));
  return { username, featuredRepos, hiddenRepos, externalRepos, token: env.GITHUB_TOKEN?.trim() || undefined };
}
